local M = {}

function M.set(scheme)
    local col16 = scheme.base16
    local col30 = scheme.base30

    return {
        DevIconAac                  = { bg = "none" },
        DevIconAi                   = { bg = "none" },
        DevIconAlmalinux            = { bg = "none" },
        DevIconAlpine               = { fg = col30.blue, ctermfg = 12, bg = "none" },
        DevIconAOSC                 = { fg = col30.red, ctermfg = 9, bg = "none" },
        DevIconApp                  = { bg = "none" },
        DevIconApple                = { fg = col30.light_grey, ctermfg = 7, bg = "none" },
        DevIconAppleScript          = { link = "DevIconApple" },
        DevIconArch                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconArtix                = { link = "DevIconArch" },
        DevIconAvif                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconAwk                  = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconAzureCli             = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconBabelrc              = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconBash                 = { link = "DevIconSh" },
        DevIconBashProfile          = { link = "DevIconSh" },
        DevIconBashrc               = { link = "DevIconSh" },
        DevIconBat                  = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconBazel                = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconBazelBuild           = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconBibTeX               = { bg = "none" },
        DevIconBazelWorkspace       = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconBinaryGLTF           = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconBmp                  = { bg = "none" },
        DevIconBrewfile             = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconBudgie               = { link = "DevIconSolus" },
        DevIconBzl                  = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconCentos               = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconc                    = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconCjs                  = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconClojure              = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconClojureC             = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconClojureDart          = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconClojureJS            = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconCMake                = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconCMakeLists           = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconCobol                = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconCoffee               = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconConf                 = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconConfigRu             = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconConfiguration        = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconCp                   = { bg = "none" },
        DevIconCPlusPlus            = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconCpp                  = { link = "DevIconCPlusPlus" },
        DevIconCrystal              = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconCs                   = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconCSharpProject        = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconCsh                  = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconCson                 = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconcss                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconCsv                  = { fg = col30.teal, ctermfg = 6, bg = "none" },
        DevIconCts                  = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconCxx                  = { link = "DevIconCPlusPlus" },
        DevIconDart                 = { fg = col30.cyan, ctermfg = 14, bg = "none" },
        DevIconDb                   = { fg = col30.light_grey, ctermfg = 7, bg = "none" },
        DevIconD                    = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIcondeb                  = { fg = col30.cyan, ctermfg = 14, bg = "none" },
        DevIconDebian               = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconDeepin               = { fg = col30.nord_blue, ctermfg = 4, bg = "none" },
        DevIconDefault              = { fg = col30.white, ctermfg = 7, bg = "none" },
        DevIconDesktopEntry         = { bg = "none" },
        DevIconDevuan               = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconDiff                 = { bg = "none" },
        DevIconDoc                  = { bg = "none" },
        DevIconDockerfile           = { fg = col30.cyan, ctermfg = 14, bg = "none" },
        DevIconDocx                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconDrools               = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconDropbox              = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconDsStore              = { bg = "none" },
        DevIconDump                 = { bg = "none" },
        DevIconEditorConfig         = { bg = "none" },
        DevIconEdn                  = { bg = "none" },
        DevIconEex                  = { bg = "none" },
        DevIconEjs                  = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconElementary           = { fg = col30.blue, ctermfg = 12, bg = "none" },
        DevIconElf                  = { bg = "none" },
        DevIconElm                  = { bg = "none" },
        DevIconEmbeddedOpenTypeFont = { bg = "none" },
        DevIconEndeavour            = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconEnv                  = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconEpp                  = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconErb                  = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconErl                  = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconEslintIgnore         = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconEslintrc             = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconEx                   = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconExe                  = { bg = "none" },
        DevIconExs                  = { bg = "none" },
        DevIconFavicon              = { bg = "none" },
        DevIconFedora               = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconFennel               = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconFish                 = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconFlac                 = { bg = "none" },
        DevIconFortran              = { fg = col30.dark_purple, ctermfg = 5, bg = "none" },
        DevIconFreeBSD              = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconFs                   = { link = "DevIconFsharp" },
        DevIconFsharp               = { fg = col30.cyan, ctermfg = 14, bg = "none" },
        DevIconFsi                  = { link = "DevIconFsharp" },
        DevIconFsscript             = { link = "DevIconFsharp" },
        DevIconFsx                  = { link = "DevIconFsharp" },
        DevIconGDScript             = { link = "DevIconGodotProject" },
        DevIconGemfile              = { link = "DevIconRuby" },
        DevIconGemspec              = { link = "DevIconRuby" },
        DevIconGentoo               = { fg = col30.pink, ctermfg = 13, bg = "none" },
        DevIconGif                  = { bg = "none" },
        DevIconGitAttributes        = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGitCommit            = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGitConfig            = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGitIgnore            = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGitlabCI             = { fg = col30.sun, ctermfg = 3, bg = "none" },
        DevIconGitLogo              = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGitModules           = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGo                   = { fg = col30.cyan, ctermfg = 14, bg = "none" },
        DevIconGodotProject         = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconGraphQL              = { fg = col30.dark_purple, ctermfg = 5, bg = "none" },
        DevIconGruntfile            = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGuix                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconGulpfile             = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconGvimrc               = { link = "DevIconVim" },
        DevIconHaml                 = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconH                    = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconHbs                  = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconHeex                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconHh                   = { bg = "none" },
        DevIconHpp                  = { link = "DevIconCPlusPlus" },
        DevIconHrl                  = { bg = "none" },
        DevIconHaskell              = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconHs                   = { link = "DevIconHaskell" },
        DevIconHtm                  = { link = "DevIconHtml" },
        DevIconhtml                 = { link = "DevIconHtml" },
        DevIconHtml                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconHuff                 = { bg = "none" },
        DevIconHurl                 = { bg = "none" },
        DevIconHxx                  = { link = "DevIconCPlusPlus" },
        DevIconIco                  = { bg = "none" },
        DevIconIllumos              = { fg = col30.red, ctermfg = 9, bg = "none" },
        DevIconImportConfiguration  = { bg = "none" },
        DevIconIni                  = { bg = "none" },
        DevIconJava                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconJavaScriptReactSpec  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconJavaScriptReactTest  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconJl                   = { bg = "none" },
        DevIconjpeg                 = { fg = col30.dark_purple, ctermfg = 5, bg = "none" },
        DevIconJpegXl               = { bg = "none" },
        DevIconjpg                  = { fg = col30.dark_purple, ctermfg = 5, bg = "none" },
        DevIconJs                   = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconjs                   = { link = "DevIconJs" },
        DevIconJson                 = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconJson5                = { link = "DevIconJson" },
        DevIconJsonc                = { link = "DevIconJson" },
        DevIconJSX                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconKali                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconKotlin               = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconKotlinScript         = { link = "DevIconKotlin" },
        DevIconKsh                  = { link = "DevIconSh" },
        DevIconkt                   = { link = "DevIconKotlin" },
        DevIconLeex                 = { bg = "none" },
        DevIconLess                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconLhs                  = { bg = "none" },
        DevIconLicense              = { bg = "none" },
        DevIconLinux                = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconLiquid               = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconlock                 = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconLog                  = { bg = "none" },
        DevIconLua                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconlua                  = { link = "DevIconLua" },
        DevIconLuau                 = { link = "DevIconLua" },
        DevIconLuaurc               = { link = "DevIconLua" },
        DevIconM4A                  = { bg = "none" },
        DevIconM4V                  = { bg = "none" },
        DevIconMageia               = { bg = "none" },
        DevIconMakefile             = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconManjaro              = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconMarkdown             = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconMaterial             = { bg = "none" },
        DevIconMd                   = { link = "Markdown" },
        DevIconMdx                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconMint                 = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconMixLock              = { bg = "none" },
        DevIconMjs                  = { fg = col30.cyan, ctermfg = 6, bg = "none" },
        DevIconMkv                  = { bg = "none" },
        DevIconMl                   = { bg = "none" },
        DevIconMli                  = { bg = "none" },
        DevIconMotoko               = { bg = "none" },
        DevIconMOV                  = { bg = "none" },
        DevIconmp3                  = { bg = "none" },
        DevIconmp4                  = { bg = "none" },
        DevIconMts                  = { bg = "none" },
        DevIconMustache             = { bg = "none" },
        DevIconNim                  = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconNix                  = { fg = col30.cyan, ctermfg = 6, bg = "none" },
        DevIconNixOS                = { link = "DevIconNix" },
        DevIconNodeModules          = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconNPMIgnore            = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconNPMrc                = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconNswag                = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconOgg                  = { bg = "none" },
        DevIconOpenBSD              = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconOpenSUSE             = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconopenSUSE             = { link = "DevIconOpenSUSE" },
        DevIconOpenTypeFont         = { bg = "none" },
        DevIconOPUS                 = { bg = "none" },
        DevIconOrgMode              = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconout                  = { bg = "none" },
        DevIconPackageJson          = { link = "DevIconJson" },
        DevIconPackageLockJson      = { link = "DevIconJson" },
        DevIconPackedResource       = { bg = "none" },
        DevIconParrot               = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconPdf                  = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconPhp                  = { bg = "none" },
        DevIconPl                   = { bg = "none" },
        DevIconPm                   = { bg = "none" },
        DevIconpng                  = { bg = "none" },
        DevIconPop_OS               = { fg = col30.teal, ctermfg = 6, bg = "none" },
        DevIconPp                   = { bg = "none" },
        DevIconPpt                  = { bg = "none" },
        DevIconPrisma               = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconProcfile             = { bg = "none" },
        DevIconProlog               = { bg = "none" },
        DevIconPsb                  = { bg = "none" },
        DevIconPsd                  = { bg = "none" },
        DevIconPsManifestfile       = { bg = "none" },
        DevIconPsScriptfile         = { bg = "none" },
        DevIconPsScriptModulefile   = { bg = "none" },
        DevIconPxd                  = { bg = "none" },
        DevIconPxi                  = { bg = "none" },
        DevIconPy                   = { link = "DevIconPython" },
        DevIconPyc                  = { link = "DevIconPython" },
        DevIconPyd                  = { link = "DevIconPython" },
        DevIconpy                   = { link = "DevIconPython" },
        DevIconPyi                  = { link = "DevIconPython" },
        DevIconPyo                  = { link = "DevIconPython" },
        DevIconPython               = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconPyx                  = { link = "DevIconPython" },
        DevIconQuery                = { bg = "none" },
        DevIconRake                 = { link = "DevIconRuby" },
        DevIconRakefile             = { link = "DevIconRuby" },
        DevIconRaspberryPiOS        = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconRazorPage            = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconrb                   = { link = "DevIconRuby" },
        DevIconR                    = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconRedhat               = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconReScript             = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconReScriptInterface    = { link = "DevIconReScript" },
        DevIconRlib                 = { bg = "none" },
        DevIconRmd                  = { bg = "none" },
        DevIconRockyLinux           = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconrpm                  = { link = "DevIconRpm" },
        DevIconRpm                  = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconRproj                = { bg = "none" },
        DevIconRs                   = { link = "DevIconRust" },
        DevIconRss                  = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconRuby                 = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconRust                 = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconSabayon              = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconSass                 = { fg = col30.pink, ctermfg = 13, bg = "none" },
        DevIconsbt                  = { link = "DevIconScala" },
        DevIconScala                = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconScheme               = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconScss                 = { fg = col30.pink, ctermfg = 13, bg = "none" },
        DevIconSettingsJson         = { link = "DevIconJson" },
        DevIconSh                   = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconSig                  = { bg = "none" },
        DevIconSlackware            = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconSlim                 = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconSln                  = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconSml                  = { bg = "none" },
        DevIconSolidity             = { bg = "none" },
        DevIconSolus                = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconSpecJs               = { bg = "none" },
        DevIconSpecTs               = { bg = "none" },
        DevIconSql                  = { fg = col16.blue, ctermfg = 4, bg = "none" },
        DevIconStyl                 = { bg = "none" },
        DevIconSuo                  = { bg = "none" },
        DevIconSvelteConfig         = { link = "DevIconSvelte" },
        DevIconSvelte               = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconSvg                  = { bg = "none" },
        DevIconSwift                = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconSystemVerilog        = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconTailwindConfig       = { fg = col30.cyan, ctermfg = 6, bg = "none" },
        DevIconTcl                  = { fg = col16.blue, ctermfg = 4, bg = "none" },
        DevIconTempl                = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconTerminal             = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconTerraform            = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconTestJs               = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconTestTs               = { fg = col30.yellow, ctermfg = 11, bg = "none" },
        DevIconTex                  = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconTextResource         = { bg = "none" },
        DevIconTextScene            = { bg = "none" },
        DevIconTFVars               = { link = "DevIconTerraform" },
        DevIcontoml                 = { link = "DevIconToml" },
        DevIconToml                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconTor                  = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconTrueTypeFont         = { bg = "none" },
        DevIconTSConfig             = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconts                   = { link = "DevIconTs" },
        DevIconTs                   = { fg = col30.teal, ctermfg = 6, bg = "none" },
        DevIconTSX                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconttf                  = { bg = "none" },
        DevIconTwig                 = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconTxt                  = { bg = "none" },
        DevIconTypeScriptReactSpec  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconTypeScriptReactTest  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconUbuntu               = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconVagrantfile          = { fg = col30.red, ctermfg = 1, bg = "none" },
        DevIconVala                 = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconVerilog              = { fg = col30.purple, ctermfg = 5, bg = "none" },
        DevIconVHDL                 = { bg = "none" },
        DevIconVim                  = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconVimrc                = { link = "DevIconVim" },
        DevIconVlang                = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconVoid                 = { fg = col30.green, ctermfg = 2, bg = "none" },
        DevIconvue                  = { fg = col30.vibrant_green, ctermfg = 10, bg = "none" },
        DevIconWasm                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconWav                  = { bg = "none" },
        DevIconWebmanifest          = { bg = "none" },
        DevIconWebm                 = { bg = "none" },
        DevIconWebOpenFontFormat    = { bg = "none" },
        DevIconWebpack              = { bg = "none" },
        DevIconWebp                 = { bg = "none" },
        DevIconWindows              = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconwoff                 = { bg = "none" },
        DevIconwoff2                = { bg = "none" },
        DevIconXaml                 = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconXcPlayground         = { bg = "none" },
        DevIconXls                  = { bg = "none" },
        DevIconXlsx                 = { bg = "none" },
        DevIconXml                  = { fg = col30.blue, ctermfg = 4, bg = "none" },
        DevIconXul                  = { link = "DevIconXul" },
        DevIconxz                   = { bg = "none" },
        DevIconYaml                 = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconYml                  = { link = "DevIconYaml" },
        DevIconZig                  = { fg = col30.orange, ctermfg = 3, bg = "none" },
        DevIconzip                  = { bg = "none" },
        DevIconZorin                = { fg = col30.cyan, ctermfg = 6, bg = "none" },
        DevIconZsh                  = { fg = col16.color03, ctermfg = 8, bg = "none" },
        DevIconZshenv               = { link = "DevIconZsh" },
        DevIconZshprofile           = { link = "DevIconZsh" },
        DevIconZshrc                = { link = "DevIconZsh" },
    }
end

return M
