local M = { }

function M.set(scheme)
    local col16 = scheme.base16
    local col30 = scheme.base30

    return {
        DevIconAac                  = { },
        DevIconAi                   = { },
        DevIconAlmalinux            = { },
        DevIconAlpine               = { fg = col30.blue, ctermfg = 12 },
        DevIconAOSC                 = { fg = col30.red, ctermfg = 9 },
        DevIconApp                  = { },
        DevIconApple                = { fg = col30.light_grey, ctermfg = 7 },
        DevIconAppleScript          = { link = "DevIconApple" },
        DevIconArch                 = { fg = col30.blue, ctermfg = 4 },
        DevIconArtix                = { link = "DevIconArch" },
        DevIconAvif                 = { fg = col30.orange, ctermfg = 3 },
        DevIconAwk                  = { fg = col30.red, ctermfg = 1 },
        DevIconAzureCli             = { fg = col30.blue, ctermfg = 4 },
        DevIconBabelrc              = { fg = col30.yellow, ctermfg = 11 },
        DevIconBash                 = { link = "DevIconSh" },
        DevIconBashProfile          = { link = "DevIconSh" },
        DevIconBashrc               = { link = "DevIconSh" },
        DevIconBat                  = { fg = col16.color03, ctermfg = 8 },
        DevIconBazel                = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconBazelBuild           = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconBibTeX               = { },
        DevIconBazelWorkspace       = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconBinaryGLTF           = { fg = col30.green, ctermfg = 2 },
        DevIconBmp                  = { },
        DevIconBrewfile             = { fg = col30.orange, ctermfg = 3 },
        DevIconBudgie               = { link = "DevIconSolus" },
        DevIconBzl                  = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconCentos               = { fg = col30.purple, ctermfg = 5 },
        DevIconc                    = { fg = col30.blue, ctermfg = 4 },
        DevIconCjs                  = { fg = col30.green, ctermfg = 2 },
        DevIconClojure              = { fg = col30.blue, ctermfg = 4 },
        DevIconClojureC             = { fg = col30.blue, ctermfg = 4 },
        DevIconClojureDart          = { fg = col30.blue, ctermfg = 4 },
        DevIconClojureJS            = { fg = col30.blue, ctermfg = 4 },
        DevIconCMake                = { fg = col30.red, ctermfg = 1 },
        DevIconCMakeLists           = { fg = col30.red, ctermfg = 1 },
        DevIconCobol                = { fg = col30.blue, ctermfg = 4 },
        DevIconCoffee               = { fg = col16.color03, ctermfg = 8 },
        DevIconConf                 = { fg = col16.color03, ctermfg = 8 },
        DevIconConfigRu             = { fg = col30.red, ctermfg = 1 },
        DevIconConfiguration        = { fg = col16.color03, ctermfg = 8 },
        DevIconCp                   = { },
        DevIconCPlusPlus            = { fg = col30.blue, ctermfg = 4 },
        DevIconCpp                  = { link = "DevIconCPlusPlus" },
        DevIconCrystal              = { fg = col16.color03, ctermfg = 8 },
        DevIconCs                   = { fg = col30.purple, ctermfg = 5 },
        DevIconCSharpProject        = { fg = col30.purple, ctermfg = 5 },
        DevIconCsh                  = { fg = col16.color03, ctermfg = 8 },
        DevIconCson                 = { fg = col16.color03, ctermfg = 8 },
        DevIconcss                  = { fg = col30.blue, ctermfg = 4 },
        DevIconCsv                  = { fg = col30.teal, ctermfg = 6 },
        DevIconCts                  = { fg = col30.orange, ctermfg = 3 },
        DevIconCxx                  = { link = "DevIconCPlusPlus" },
        DevIconDart                 = { fg = col30.cyan, ctermfg = 14 },
        DevIconDb                   = { fg = col30.light_grey, ctermfg = 7 },
        DevIconD                    = { fg = col30.red, ctermfg = 1 },
        DevIcondeb                  = { fg = col30.cyan, ctermfg = 14 },
        DevIconDebian               = { fg = col30.red, ctermfg = 1 },
        DevIconDeepin               = { fg = col30.nord_blue, ctermfg = 4 },
        DevIconDefault              = { fg = col30.white, ctermfg = 7 },
        DevIconDesktopEntry         = { },
        DevIconDevuan               = { fg = col30.red, ctermfg = 1 },
        DevIconDiff                 = { },
        DevIconDoc                  = { },
        DevIconDockerfile           = { fg = col30.cyan, ctermfg = 14 },
        DevIconDocx                 = { fg = col30.blue, ctermfg = 4 },
        DevIconDrools               = { fg = col30.red, ctermfg = 1 },
        DevIconDropbox              = { fg = col30.blue, ctermfg = 4 },
        DevIconDsStore              = { },
        DevIconDump                 = { },
        DevIconEditorConfig         = { },
        DevIconEdn                  = { },
        DevIconEex                  = { },
        DevIconEjs                  = { fg = col30.red, ctermfg = 1 },
        DevIconElementary           = { fg = col30.blue, ctermfg = 12 },
        DevIconElf                  = { },
        DevIconElm                  = { },
        DevIconEmbeddedOpenTypeFont = { },
        DevIconEndeavour            = { fg = col30.purple, ctermfg = 5 },
        DevIconEnv                  = { fg = col30.yellow, ctermfg = 11 },
        DevIconEpp                  = { fg = col30.yellow, ctermfg = 11 },
        DevIconErb                  = { fg = col30.red, ctermfg = 1 },
        DevIconErl                  = { fg = col30.red, ctermfg = 1 },
        DevIconEslintIgnore         = { fg = col30.blue, ctermfg = 4 },
        DevIconEslintrc             = { fg = col30.blue, ctermfg = 4 },
        DevIconEx                   = { fg = col30.orange, ctermfg = 3 },
        DevIconExe                  = { },
        DevIconExs                  = { },
        DevIconFavicon              = { },
        DevIconFedora               = { fg = col30.blue, ctermfg = 4 },
        DevIconFennel               = { fg = col30.green, ctermfg = 2 },
        DevIconFish                 = { fg = col30.green, ctermfg = 2 },
        DevIconFlac                 = { },
        DevIconFortran              = { fg = col30.dark_purple, ctermfg = 5 },
        DevIconFreeBSD              = { fg = col30.red, ctermfg = 1 },
        DevIconFs                   = { link = "DevIconFsharp" },
        DevIconFsharp               = { fg = col30.cyan, ctermfg = 14 },
        DevIconFsi                  = { link = "DevIconFsharp" },
        DevIconFsscript             = { link = "DevIconFsharp" },
        DevIconFsx                  = { link = "DevIconFsharp" },
        DevIconGDScript             = { link = "DevIconGodotProject" },
        DevIconGemfile              = { link = "DevIconRuby" },
        DevIconGemspec              = { link = "DevIconRuby" },
        DevIconGentoo               = { fg = col30.pink, ctermfg = 13 },
        DevIconGif                  = { },
        DevIconGitAttributes        = { fg = col30.orange, ctermfg = 3 },
        DevIconGitCommit            = { fg = col30.orange, ctermfg = 3 },
        DevIconGitConfig            = { fg = col30.orange, ctermfg = 3 },
        DevIconGitIgnore            = { fg = col30.orange, ctermfg = 3 },
        DevIconGitlabCI             = { fg = col30.sun, ctermfg = 3 },
        DevIconGitLogo              = { fg = col30.orange, ctermfg = 3 },
        DevIconGitModules           = { fg = col30.orange, ctermfg = 3 },
        DevIconGo                   = { fg = col30.cyan, ctermfg = 14 },
        DevIconGodotProject         = { fg = col30.blue, ctermfg = 4 },
        DevIconGraphQL              = { fg = col30.dark_purple, ctermfg = 5 },
        DevIconGruntfile            = { fg = col30.orange, ctermfg = 3 },
        DevIconGuix                 = { fg = col30.orange, ctermfg = 3 },
        DevIconGulpfile             = { fg = col30.red, ctermfg = 1 },
        DevIconGvimrc               = { link = "DevIconVim" },
        DevIconHaml                 = { fg = col30.yellow, ctermfg = 11 },
        DevIconH                    = { fg = col30.blue, ctermfg = 4 },
        DevIconHbs                  = { fg = col30.orange, ctermfg = 3 },
        DevIconHeex                 = { fg = col30.orange, ctermfg = 3 },
        DevIconHh                   = { },
        DevIconHpp                  = { link = "DevIconCPlusPlus" },
        DevIconHrl                  = { },
        DevIconHaskell              = { fg = col30.purple, ctermfg = 5 },
        DevIconHs                   = { link = "DevIconHaskell" },
        DevIconHtm                  = { link = "DevIconHtml" },
        DevIconhtml                 = { link = "DevIconHtml" },
        DevIconHtml                 = { fg = col30.orange, ctermfg = 3 },
        DevIconHuff                 = { },
        DevIconHurl                 = { },
        DevIconHxx                  = { link = "DevIconCPlusPlus" },
        DevIconIco                  = { },
        DevIconIllumos              = { fg = col30.red, ctermfg = 9 },
        DevIconImportConfiguration  = { },
        DevIconIni                  = { },
        DevIconJava                 = { fg = col30.orange, ctermfg = 3 },
        DevIconJavaScriptReactSpec  = { fg = col30.blue, ctermfg = 4 },
        DevIconJavaScriptReactTest  = { fg = col30.blue, ctermfg = 4 },
        DevIconJl                   = { },
        DevIconjpeg                 = { fg = col30.dark_purple, ctermfg = 5 },
        DevIconJpegXl               = { },
        DevIconjpg                  = { fg = col30.dark_purple, ctermfg = 5 },
        DevIconJs                   = { fg = col30.yellow, ctermfg = 11 },
        DevIconjs                   = { link = "DevIconJs" },
        DevIconJson                 = { fg = col30.yellow, ctermfg = 11 },
        DevIconJson5                = { link = "DevIconJson" },
        DevIconJsonc                = { link = "DevIconJson" },
        DevIconJSX                  = { fg = col30.blue, ctermfg = 4 },
        DevIconKali                 = { fg = col30.blue, ctermfg = 4 },
        DevIconKotlin               = { fg = col30.purple, ctermfg = 5 },
        DevIconKotlinScript         = { link = "DevIconKotlin" },
        DevIconKsh                  = { link = "DevIconSh" },
        DevIconkt                   = { link = "DevIconKotlin" },
        DevIconLeex                 = { },
        DevIconLess                 = { fg = col30.blue, ctermfg = 4 },
        DevIconLhs                  = { },
        DevIconLicense              = { },
        DevIconLinux                = { fg = col30.yellow, ctermfg = 11 },
        DevIconLiquid               = { fg = col30.blue, ctermfg = 4 },
        DevIconlock                 = { fg = col30.red, ctermfg = 1 },
        DevIconLog                  = { },
        DevIconLua                  = { fg = col30.blue, ctermfg = 4 },
        DevIconlua                  = { link = "DevIconLua" },
        DevIconLuau                 = { link = "DevIconLua" },
        DevIconLuaurc               = { link = "DevIconLua" },
        DevIconM4A                  = { },
        DevIconM4V                  = { },
        DevIconMageia               = { },
        DevIconMakefile             = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconManjaro              = { fg = col30.green, ctermfg = 2 },
        DevIconMarkdown             = { fg = col16.color03, ctermfg = 8 },
        DevIconMaterial             = { },
        DevIconMd                   = { link = "Markdown" },
        DevIconMdx                  = { fg = col30.blue, ctermfg = 4 },
        DevIconMint                 = { fg = col30.green, ctermfg = 2 },
        DevIconMixLock              = { },
        DevIconMjs                  = { fg = col30.cyan, ctermfg = 6 },
        DevIconMkv                  = { },
        DevIconMl                   = { },
        DevIconMli                  = { },
        DevIconMotoko               = { },
        DevIconMOV                  = { },
        DevIconmp3                  = { },
        DevIconmp4                  = { },
        DevIconMts                  = { },
        DevIconMustache             = { },
        DevIconNim                  = { fg = col30.yellow, ctermfg = 11 },
        DevIconNix                  = { fg = col30.cyan, ctermfg = 6 },
        DevIconNixOS                = { link = "DevIconNix" },
        DevIconNodeModules          = { fg = col30.green, ctermfg = 2 },
        DevIconNPMIgnore            = { fg = col30.green, ctermfg = 2 },
        DevIconNPMrc                = { fg = col30.green, ctermfg = 2 },
        DevIconNswag                = { fg = col30.blue, ctermfg = 4 },
        DevIconOgg                  = { },
        DevIconOpenBSD              = { fg = col30.yellow, ctermfg = 11 },
        DevIconOpenSUSE             = { fg = col30.green, ctermfg = 2 },
        DevIconopenSUSE             = { link = "DevIconOpenSUSE" },
        DevIconOpenTypeFont         = { },
        DevIconOPUS                 = { },
        DevIconOrgMode              = { fg = col30.green, ctermfg = 2 },
        DevIconout                  = { },
        DevIconPackageJson          = { link = "DevIconJson" },
        DevIconPackageLockJson      = { link = "DevIconJson" },
        DevIconPackedResource       = { },
        DevIconParrot               = { fg = col30.green, ctermfg = 2 },
        DevIconPdf                  = { fg = col30.red, ctermfg = 1 },
        DevIconPhp                  = { },
        DevIconPl                   = { },
        DevIconPm                   = { },
        DevIconpng                  = { },
        DevIconPop_OS               = { fg = col30.teal, ctermfg = 6 },
        DevIconPp                   = { },
        DevIconPpt                  = { },
        DevIconPrisma               = { fg = col16.color03, ctermfg = 8 },
        DevIconProcfile             = { },
        DevIconProlog               = { },
        DevIconPsb                  = { },
        DevIconPsd                  = { },
        DevIconPsManifestfile       = { },
        DevIconPsScriptfile         = { },
        DevIconPsScriptModulefile   = { },
        DevIconPxd                  = { },
        DevIconPxi                  = { },
        DevIconPy                   = { link = "DevIconPython" },
        DevIconPyc                  = { link = "DevIconPython" },
        DevIconPyd                  = { link = "DevIconPython" },
        DevIconpy                   = { link = "DevIconPython" },
        DevIconPyi                  = { link = "DevIconPython" },
        DevIconPyo                  = { link = "DevIconPython" },
        DevIconPython               = { fg = col30.blue, ctermfg = 4 },
        DevIconPyx                  = { link = "DevIconPython" },
        DevIconQuery                = { },
        DevIconRake                 = { link = "DevIconRuby" },
        DevIconRakefile             = { link = "DevIconRuby" },
        DevIconRaspberryPiOS        = { fg = col30.red, ctermfg = 1 },
        DevIconRazorPage            = { fg = col30.blue, ctermfg = 4 },
        DevIconrb                   = { link = "DevIconRuby" },
        DevIconR                    = { fg = col30.blue, ctermfg = 4 },
        DevIconRedhat               = { fg = col30.red, ctermfg = 1 },
        DevIconReScript             = { fg = col30.red, ctermfg = 1 },
        DevIconReScriptInterface    = { link = "DevIconReScript" },
        DevIconRlib                 = { },
        DevIconRmd                  = { },
        DevIconRockyLinux           = { fg = col30.green, ctermfg = 2 },
        DevIconrpm                  = { link = "DevIconRpm" },
        DevIconRpm                  = { fg = col30.orange, ctermfg = 3 },
        DevIconRproj                = { },
        DevIconRs                   = { link = "DevIconRust" },
        DevIconRss                  = { fg = col30.orange, ctermfg = 3 },
        DevIconRuby                 = { fg = col30.red, ctermfg = 1 },
        DevIconRust                 = { fg = col16.color03, ctermfg = 8 },
        DevIconSabayon              = { fg = col16.color03, ctermfg = 8 },
        DevIconSass                 = { fg = col30.pink, ctermfg = 13 },
        DevIconsbt                  = { link = "DevIconScala" },
        DevIconScala                = { fg = col30.red, ctermfg = 1 },
        DevIconScheme               = { fg = col16.color03, ctermfg = 8 },
        DevIconScss                 = { fg = col30.pink, ctermfg = 13 },
        DevIconSettingsJson         = { link = "DevIconJson" },
        DevIconSh                   = { fg = col16.color03, ctermfg = 8 },
        DevIconSig                  = { },
        DevIconSlackware            = { fg = col30.blue, ctermfg = 4 },
        DevIconSlim                 = { fg = col30.orange, ctermfg = 3 },
        DevIconSln                  = { fg = col30.purple, ctermfg = 5 },
        DevIconSml                  = { },
        DevIconSolidity             = { },
        DevIconSolus                = { fg = col16.color03, ctermfg = 8 },
        DevIconSpecJs               = { },
        DevIconSpecTs               = { },
        DevIconSql                  = { fg = col16.blue, ctermfg = 4 },
        DevIconStyl                 = { },
        DevIconSuo                  = { },
        DevIconSvelteConfig         = { link = "DevIconSvelte" },
        DevIconSvelte               = { fg = col30.red, ctermfg = 1 },
        DevIconSvg                  = { },
        DevIconSwift                = { fg = col30.red, ctermfg = 1 },
        DevIconSystemVerilog        = { fg = col30.purple, ctermfg = 5 },
        DevIconTailwindConfig       = { fg = col30.cyan, ctermfg = 6 },
        DevIconTcl                  = { fg = col16.blue, ctermfg = 4 },
        DevIconTempl                = { fg = col30.yellow, ctermfg = 11 },
        DevIconTerminal             = { fg = col16.color03, ctermfg = 8 },
        DevIconTerraform            = { fg = col30.purple, ctermfg = 5 },
        DevIconTestJs               = { fg = col30.yellow, ctermfg = 11 },
        DevIconTestTs               = { fg = col30.yellow, ctermfg = 11 },
        DevIconTex                  = { fg = col16.color03, ctermfg = 8 },
        DevIconTextResource         = { },
        DevIconTextScene            = { },
        DevIconTFVars               = { link = "DevIconTerraform" },
        DevIcontoml                 = { link = "DevIconToml" },
        DevIconToml                 = { fg = col30.blue, ctermfg = 4 },
        DevIconTor                  = { fg = col30.purple, ctermfg = 5 },
        DevIconTrueTypeFont         = { },
        DevIconTSConfig             = { fg = col30.green, ctermfg = 2 },
        DevIconts                   = { link = "DevIconTs" },
        DevIconTs                   = { fg = col30.teal, ctermfg = 6 },
        DevIconTSX                  = { fg = col30.blue, ctermfg = 4 },
        DevIconttf                  = { },
        DevIconTwig                 = { fg = col30.green, ctermfg = 2 },
        DevIconTxt                  = { },
        DevIconTypeScriptReactSpec  = { fg = col30.blue, ctermfg = 4 },
        DevIconTypeScriptReactTest  = { fg = col30.blue, ctermfg = 4 },
        DevIconUbuntu               = { fg = col30.orange, ctermfg = 3 },
        DevIconVagrantfile          = { fg = col30.red, ctermfg = 1 },
        DevIconVala                 = { fg = col30.purple, ctermfg = 5 },
        DevIconVerilog              = { fg = col30.purple, ctermfg = 5 },
        DevIconVHDL                 = { },
        DevIconVim                  = { fg = col30.green, ctermfg = 2 },
        DevIconVimrc                = { link = "DevIconVim" },
        DevIconVlang                = { fg = col30.blue, ctermfg = 4 },
        DevIconVoid                 = { fg = col30.green, ctermfg = 2 },
        DevIconvue                  = { fg = col30.vibrant_green, ctermfg = 10 },
        DevIconWasm                 = { fg = col30.blue, ctermfg = 4 },
        DevIconWav                  = { },
        DevIconWebmanifest          = { },
        DevIconWebm                 = { },
        DevIconWebOpenFontFormat    = { },
        DevIconWebpack              = { },
        DevIconWebp                 = { },
        DevIconWindows              = { fg = col30.blue, ctermfg = 4 },
        DevIconwoff                 = { },
        DevIconwoff2                = { },
        DevIconXaml                 = { fg = col30.blue, ctermfg = 4 },
        DevIconXcPlayground         = { },
        DevIconXls                  = { },
        DevIconXlsx                 = { },
        DevIconXml                  = { fg = col30.blue, ctermfg = 4 },
        DevIconXul                  = { link = "DevIconXul" },
        DevIconxz                   = { },
        DevIconYaml                 = { fg = col16.color03, ctermfg = 8 },
        DevIconYml                  = { link = "DevIconYaml" },
        DevIconZig                  = { fg = col30.orange, ctermfg = 3 },
        DevIconzip                  = { },
        DevIconZorin                = { fg = col30.cyan, ctermfg = 6 },
        DevIconZsh                  = { fg = col16.color03, ctermfg = 8 },
        DevIconZshenv               = { link = "DevIconZsh" },
        DevIconZshprofile           = { link = "DevIconZsh" },
        DevIconZshrc                = { link = "DevIconZsh" },
    }
end

return M
